monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        info:
            type: stream
            path: "%kernel.logs_dir%/info_%kernel.environment%.log"
            level: info
        warning:
            type: stream
            path: "%kernel.logs_dir%/warning_%kernel.environment%.log"
            level: warning