version: "3.8"

services:

  # PHP Service
  php:
    container_name: symfony-base
    restart: unless-stopped
    ports:
      - "8000:8000"
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    networks:
      - api-network
    depends_on:
      - mysql
    command: symfony serve --dir=./public --port=8000

  # MySQL Service
  mysql:
    container_name: symfony-mysql
    build:
      context: ./docker/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mysql/env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - api-network
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

networks:
  api-network:
    name: api-network

volumes:
  mysql-data:
