home_controllers:
  resource: ../../src/Home/Infrastructure/REST/Controller
  type: attribute

user_controllers:
  resource: ../../src/User/Infrastructure/REST/Controller
  type: attribute

kernel:
  resource: App\Kernel
  type: attribute