services:
  _defaults:
    autowire: true  # Enables automatic injection of dependencies.
    autoconfigure: true  # Enables automatic configuration of services.

  # -- COMMON MODULE --

  Common\:
    resource: ../../../src/Common

  Common\Infrastructure\Adapter\Listener\JsonExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  Common\Infrastructure\Adapter\Listener\RequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  # Monolog
  Monolog\Logger:
    arguments:
      $name: 'request'
      $handlers: [ '@monolog.handler' ]

  monolog.handler:
    class: Monolog\Handler\StreamHandler
    arguments:
      $level: 'error'
      $stream: '%kernel.logs_dir%/exception_%kernel.environment%.log'

  Common\Infrastructure\Implementation\Logger\MonologLogger:
    arguments:
      $logger: '@Monolog\Logger'