services:
  _defaults:
    autowire: true
    autoconfigure: true

  # -- USER MODULE --

  User\:
    resource: ../../../src/User

  User\Infrastructure\REST\Controller\:
    resource: ../../../src/User/Infrastructure/REST/Controller
    tags: [ controller.service_arguments ]

  # Instance configuration for specific classes.
  _instanceof:
    Common\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ user.domain_event_subscriber ]
    Common\Application\Bus\Command\CommandHandler:
      tags: [ user.command_handler ]
    Common\Application\Bus\Query\QueryHandler:
      tags: [ user.query_handler ]

  # Defines the InMemorySymfonyCommandBus service.
  Common\Infrastructure\Bus\Command\Symfony\InMemorySymfonyCommandBus:
    arguments: [ !tagged_iterator user.command_handler ]  # Injects all tagged command handlers.

  # Defines the InMemorySymfonyQueryBus service.
  Common\Infrastructure\Bus\Query\Symfony\InMemorySymfonyQueryBus:
    arguments: [ !tagged_iterator user.query_handler ]  # Injects all tagged query handlers.

  # In-Memory Event Bus
  # Defines the InMemorySymfonyEventBus service.
  Common\Infrastructure\Bus\Event\Symfony\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged_iterator user.domain_event_subscriber ]  # Injects all tagged domain event subscribers.
    lazy: true  # The service is only initialized when it's actually needed.