services:
  _defaults:
    autowire: true
    autoconfigure: true

  # -- HOME MODULE --

  Home\:
    resource: ../../../src/Home

  Home\Infrastructure\Adapter\REST\Controller\:
    resource: ../../../src/Home/Infrastructure/Adapter/REST/Controller
    tags: [ controller.service_arguments ]